services:
  web:
    build:
      context: .
    container_name: django_web
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/hotels_db
    networks:
      - shared_network
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
    name: shared_network
