# Generated by Django 5.1.4 on 2024-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image_path', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hotels',
                'managed': False,
            },
        ),
    ]
