# Generated by Django 5.1.4 on 2024-12-31 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_newhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='management_app.newhotel')),
            ],
            options={
                'db_table': 'hotel_summaries',
            },
        ),
    ]
