# Generated by Django 5.1.4 on 2025-01-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_newhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRatingReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_id', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'hotel_ratings_reviews',
            },
        ),
        migrations.CreateModel(
            name='HotelSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_id', models.IntegerField()),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'hotel_summaries',
            },
        ),
    ]
