# Generated by Django 5.1.4 on 2024-12-31 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_hotelsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRatingReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.TextField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_reviews', to='management_app.newhotel')),
            ],
            options={
                'db_table': 'hotel_ratings_reviews',
            },
        ),
    ]
