# Generated by Django 5.1.4 on 2024-12-31 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_hotelratingreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelratingreview',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotelsummary',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotelratingreview',
            name='hotel',
            field=models.OneToOneField(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management_app.newhotel'),
        ),
        migrations.AlterField(
            model_name='hotelsummary',
            name='hotel',
            field=models.OneToOneField(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management_app.newhotel'),
        ),
    ]
